### ISSUE TITLE
Issue while running teaser.py

### ISSUE THREAD

**Issue by gupta-plantgenevo** [Cibiv/Teaser#12]
I am having issues like 
self.config["cache_directory"] = os.path.abspath(self.config["cache_directory"])
KeyError: 'cache_directory'
and
abs_test_dirs = [os.path.abspath(dir) for dir in self.config["test_directories"]]
KeyError: 'test_directories'

I looked at the code and I don't understand how to resolve it. Any help will be much appreciated.

**Comment by fritzsedlazeck** [comment]
Hi,
can you forward the whole error msg plus your config file?
Thanks
Fritz

**Comment by gupta-plantgenevo** [comment]
Hi,

The config file is attached and the error message is as follow:

$ ./teaser.py trifida_test.yaml

importing libraries...

Loaded configuration /softwares/Teaser/setups/trifida_test.yaml

[10:30:44] [Main        ] Except, exception: Traceback (most recent call
last):

  File "./teaser.py", line 950, in main

    self.initFromArgs()

  File "./teaser.py", line 710, in initFromArgs

    self.convertConfigPathsToAbs()

  File "./teaser.py", line 643, in convertConfigPathsToAbs

    self.config["cache_directory"] =
os.path.abspath(self.config["cache_directory"])

KeyError: 'cache_directory'


Traceback (most recent call last):

  File "./teaser.py", line 1091, in <module>

    mate.main()

  File "./teaser.py", line 1017, in main

    self.finalize()

  File "./teaser.py", line 1036, in finalize

    self.report.generate()

AttributeError: 'bool' object has no attribute 'generate'



I get the same error when I use the command as:

"./teaser.py trifida_test.yaml -fc -fr -rn trifida_genome"


Thanks!




Sonal Gupta
Graduate Student
Ecology and Evolutionary Biology
University of Michigan, Ann Arbor

**Comment by smolkmo** [comment]
Hi Sonal,

first of all, thanks for your report and sorry for the delayed response!

Please make sure that your config file correctly imports the base configuration, by verifying that your config file starts with the following lines:

```
include:
  - base_teaser
```

Examples for some working configuration files can also be found in our wiki: https://github.com/Cibiv/Teaser/wiki/Command-Line-Configuration

If the problem persists, please attach the exact contents of your `trifida_test.yaml `file - so we can have a closer look.

Moritz
