### ISSUE TITLE
failed to create test directory

### ISSUE THREAD

**Issue by stsmall** [Cibiv/Teaser#7]
Hi,
I installed TEASER and ran the ecoli test set. Everything finished without errors. When I tried to run real data,  copying the example_real.yaml from setups and adding paths and a new reference in reference directory, the program produces the following error: (note I also tried the --force options but it still gave the same errors). Any ideas?
thanks,
scott

importing libraries...
Loaded configuration /afs/crc.nd.edu/user/s/ssmall2/programs_that_work/Teaser/setups/wb_pacbio.yaml
Loaded configuration /afs/crc.nd.edu/user/s/ssmall2/programs_that_work/Teaser/setups/base_teaser.yaml
Loaded configuration /afs/crc.nd.edu/user/s/ssmall2/programs_that_work/Teaser/setups/base.yaml
Loaded configuration /afs/crc.nd.edu/user/s/ssmall2/programs_that_work/Teaser/setups/base_mappers.yaml
Loaded configuration /afs/crc.nd.edu/user/s/ssmall2/programs_that_work/Teaser/setups/base_parameters.yaml
Failed to include or match any files for mapper__.yaml
Failed to include or match any files for parameter__.yaml
[15:20:18] [Main        ] framework cmd:  ./teaser.py setups/wb_pacbio.yaml
[15:20:18] [Main        ] framework hash: vevev
[15:20:18] [Main        ] deployment mode: production (False)
[15:20:18] [Main        ] Test Runner Setup - ""

[15:20:18] [Main        ] Using Teaser for data set creation
[15:20:18] [Teaser      ] Init. Creating 1 test datasets.
[15:20:18] [Teaser      ] 
[15:20:18] [Teaser      ] Creating test real_pe
[15:20:18] [Teaser      ] Failed to create test directory, probably existing
[15:20:18] [Teaser      ] remove /afs/crc.nd.edu/user/s/ssmall2/programs_that_work/Teaser/wbtests_generated/real_pe/real_pe.yaml
[15:20:18] [Teaser      ] remove /afs/crc.nd.edu/user/s/ssmall2/programs_that_work/Teaser/wbtests_generated/real_pe/mapping_comparison.sam
[15:20:18] [Teaser      ] remove /afs/crc.nd.edu/user/s/ssmall2/programs_that_work/Teaser/wbtests_generated/real_pe/reads.fastq
[15:20:18] [Teaser      ] remove /afs/crc.nd.edu/user/s/ssmall2/programs_that_work/Teaser/wbtests_generated/real_pe/reads1.fastq
[15:20:18] [Teaser      ] remove /afs/crc.nd.edu/user/s/ssmall2/programs_that_work/Teaser/wbtests_generated/real_pe/reads2.fastq
[15:20:18] [Teaser      ] change directory /afs/crc.nd.edu/user/s/ssmall2/programs_that_work/Teaser/wbtests_generated/real_pe
[15:20:18] [Teaser      ] Except, exception: Traceback (most recent call last):
  File "./teaser.py", line 995, in main
    tests_teaser = self.teaser.main()
  File "/afs/crc.nd.edu/user/s/ssmall2/programs_that_work/Teaser/lib/teaser.py", line 517, in main
    self.createTest(self.tests[name])
  File "/afs/crc.nd.edu/user/s/ssmall2/programs_that_work/Teaser/lib/teaser.py", line 129, in createTest
    self.ch(test)
  File "/afs/crc.nd.edu/user/s/ssmall2/programs_that_work/Teaser/lib/teaser.py", line 473, in ch
    os.chdir(test["dir"])
OSError: [Errno 2] No such file or directory: '/afs/crc.nd.edu/user/s/ssmall2/programs_that_work/Teaser/wbtests_generated/real_pe'

[15:20:18] [ReportGen   ] This benchmark contains no tests. This could be because no tests or mappers were selected, or because generation/loading failed for all tests.
[15:20:19] [Teaser      ] Benchmark completed. Results were placed in: /afs/crc.nd.edu/user/s/ssmall2/programs_that_work/Teaser/reports/default

**Comment by smolkmo** [comment]
Hi stsmall,

Seems like Teaser was unable to create the test directory: /afs/crc.nd.edu/user/s/ssmall2/programs_that_work/Teaser/wbtests_generated/real_pe

I can think of two reasons that may cause that problem:
- You may not have the rights to write in the directory /afs/crc.nd.edu/user/s/ssmall2/programs_that_work/Teaser/wbtests_generated
- The path to the test directory already existed, but actually is a file.

Please check if you have access to the /afs/crc.nd.edu/user/s/ssmall2/programs_that_work/Teaser/wbtests_generated directory as the user you are running Teaser as, and if a file/directory real_pe exists in there.

**Comment by stsmall** [comment]
Thanks for the reply.
I have write permissions since that is same directory I ran the ecoli example from, I also do not see a directory titled /wbtests_generated. It seems that it is removed after the "failed" message. I tried running with the --force options but that didnt change any errors.
Here is text in my yaml file located at teaser/setups. The reference is in the reference directory in the teaser/references
include:
- base_teaser

teaser:
   tests:
      real_pe:
         type: real
         reference: Wb.pb.500.fasta
         paired: Yes
         import_read_files: [/scratch365/ssmall2/Wb_set1/Wbpt22_no-PX-HG_R1.fastq,/scratch365/ssmall2/Wb_set1/Wbpt22_no-PX-HG_R2.fastq]

**Comment by smolkmo** [comment]
Thanks for trying this out!

Strange, this is definitely the first time we encounter this problem.

Here are two more quick things that you could try, which may bring better luck:
- Could you try manually creating the test directory before running Teaser? (/afs/crc.nd.edu/user/s/ssmall2/programs_that_work/Teaser/wbtests_generated and possibly also /afs/crc.nd.edu/user/s/ssmall2/programs_that_work/Teaser/wbtests_generated/real_pe)
- Do you run teaser.py while being within the Teaser root directory? Not doing so still works in most cases, but has led to some path-related problems in the past.

Thanks and cheers,
Moritz

**Comment by stsmall** [comment]
Just wanted to update you. I am getting the same error, but the program is now running and didnt terminate. I have been running from root Teaser directory. Not sure what the paths issues is, I am using Anaconda python, could that be it? I will let you know if/when it finishes, but currently looks to be running.
thanks for the help and support!

importing libraries...
Loaded configuration /afs/crc.nd.edu/user/s/ssmall2/programs_that_work/Teaser/setups/wb_pacbio.yaml
Loaded configuration /afs/crc.nd.edu/user/s/ssmall2/programs_that_work/Teaser/setups/base_teaser.yaml
Loaded configuration /afs/crc.nd.edu/user/s/ssmall2/programs_that_work/Teaser/setups/base.yaml
Loaded configuration /afs/crc.nd.edu/user/s/ssmall2/programs_that_work/Teaser/setups/base_mappers.yaml
Loaded configuration /afs/crc.nd.edu/user/s/ssmall2/programs_that_work/Teaser/setups/base_parameters.yaml
Failed to include or match any files for mapper__.yaml
Failed to include or match any files for parameter__.yaml
[13:30:51] [Main        ] framework cmd:  teaser.py setups/wb_pacbio.yaml
[13:30:51] [Main        ] framework hash: vevev
[13:30:51] [Main        ] deployment mode: production (False)
[13:30:51] [Main        ] Test Runner Setup - ""

[13:30:51] [Main        ] Using Teaser for data set creation
[13:30:52] [Teaser      ] Init. Creating 1 test datasets.
[13:30:52] [Teaser      ] 
[13:30:52] [Teaser      ] Creating test real_pe
[13:30:52] [Teaser      ] Failed to create test directory, probably existing
[13:30:52] [Teaser      ] remove /afs/crc.nd.edu/user/s/ssmall2/programs_that_work/Teaser/wbtests_generated/real_pe/real_pe.yaml
[13:30:52] [Teaser      ] remove /afs/crc.nd.edu/user/s/ssmall2/programs_that_work/Teaser/wbtests_generated/real_pe/mapping_comparison.sam
[13:30:52] [Teaser      ] remove /afs/crc.nd.edu/user/s/ssmall2/programs_that_work/Teaser/wbtests_generated/real_pe/reads.fastq
[13:30:52] [Teaser      ] remove /afs/crc.nd.edu/user/s/ssmall2/programs_that_work/Teaser/wbtests_generated/real_pe/reads1.fastq
[13:30:52] [Teaser      ] remove /afs/crc.nd.edu/user/s/ssmall2/programs_that_work/Teaser/wbtests_generated/real_pe/reads2.fastq
[13:30:52] [Teaser      ] change directory /afs/crc.nd.edu/user/s/ssmall2/programs_that_work/Teaser/wbtests_generated/real_pe
[13:30:52] [Teaser      ] No target read count given for real data test, estimating using reference and avg. read length
[13:30:56] [Teaser      ] Indexing /afs/crc.nd.edu/user/s/ssmall2/programs_that_work/Teaser/references/Wb.pb.500.fasta

**Comment by stsmall** [comment]
Everything worked as expected. Guess the fix was making the directories first.
